import { Mentor } from '@/types/mentor'

export const mockMentors: Mentor[] = [
  {
    id: '1',
    name: 'Sunita Sharma',
    area: 'Gachibowli',
    subjects: ['CBSE Math', 'CBSE Science'],
    distance_km: 2.3,
    rating: 4.9,
    rate: 600,
    photo_url: 'https://i.pravatar.cc/150?img=1',
    badges: ['Top Rated', 'Verified'],
    ai_match_reason: 'Taught 200+ students in Gachibowli. 95% scored above 90%.',
  },
  {
    id: '2',
    name: 'Rajesh Kumar',
    area: 'Kondapur',
    subjects: ['JEE Physics', 'JEE Math'],
    distance_km: 3.1,
    rating: 4.8,
    rate: 1200,
    photo_url: 'https://i.pravatar.cc/150?img=2',
    badges: ['IIT Alumni', 'Expert'],
    ai_match_reason: 'IIT Bombay graduate. Specializes in JEE Advanced.',
  },
  {
    id: '3',
    name: 'Priya Reddy',
    area: 'Madhapur',
    subjects: ['NEET Biology', 'CBSE Science'],
    distance_km: 1.8,
    rating: 4.7,
    rate: 800,
    photo_url: 'https://i.pravatar.cc/150?img=3',
    badges: ['Medical Pro', 'Verified'],
    ai_match_reason: 'MBBS from Osmania. 8 years NEET coaching experience.',
  },
  {
    id: '4',
    name: 'Amit Patel',
    area: 'Gachibowli',
    subjects: ['Coding', 'CBSE Math'],
    distance_km: 2.5,
    rating: 4.6,
    rate: 500,
    photo_url: 'https://i.pravatar.cc/150?img=4',
    badges: ['Python Expert'],
    ai_match_reason: 'Ex-Amazon SDE. Teaches Python + DSA to school kids.',
  },
  {
    id: '5',
    name: 'Neha Gupta',
    area: 'Hitech City',
    subjects: ['English', 'IELTS'],
    distance_km: 4.2,
    rating: 4.9,
    rate: 700,
    photo_url: 'https://i.pravatar.cc/150?img=5',
    badges: ['Top Rated', 'IELTS 9.0'],
    ai_match_reason: 'Trained 500+ students. Average IELTS band 7.5.',
  },
  {
    id: '6',
    name: 'Vikram Singh',
    area: 'Kondapur',
    subjects: ['JEE Chemistry', 'CBSE Science'],
    distance_km: 3.5,
    rating: 4.5,
    rate: 900,
    photo_url: 'https://i.pravatar.cc/150?img=6',
    badges: ['Verified'],
    ai_match_reason: 'MSc Chemistry. Focus on organic for JEE.',
  },
  {
    id: '7',
    name: 'Ananya Rao',
    area: 'Madhapur',
    subjects: ['CBSE Math', 'CBSE Science'],
    distance_km: 1.2,
    rating: 4.8,
    rate: 550,
    photo_url: 'https://i.pravatar.cc/150?img=7',
    badges: ['Top Rated'],
    ai_match_reason: 'B.Ed certified. Makes Math fun with real examples.',
  },
  {
    id: '8',
    name: 'Karthik Menon',
    area: 'Gachibowli',
    subjects: ['Coding', 'JEE Math'],
    distance_km: 2.8,
    rating: 4.4,
    rate: 1000,
    photo_url: 'https://i.pravatar.cc/150?img=8',
    badges: ['Google SWE'],
    ai_match_reason: 'Google engineer. Weekend coding bootcamps.',
  },
  {
    id: '9',
    name: 'Divya Nair',
    area: 'Dilsukhnagar',
    subjects: ['CBSE Math', 'English'],
    distance_km: 8.5,
    rating: 4.6,
    rate: 450,
    photo_url: 'https://i.pravatar.cc/150?img=9',
    badges: ['Verified'],
    ai_match_reason: 'Patient teacher. Great for basics and fundamentals.',
  },
  {
    id: '10',
    name: 'Suresh Iyer',
    area: 'Hitech City',
    subjects: ['JEE Physics', 'JEE Math'],
    distance_km: 4.8,
    rating: 4.9,
    rate: 1500,
    photo_url: 'https://i.pravatar.cc/150?img=10',
    badges: ['IIT Alumni', 'Top Rated', 'Expert'],
    ai_match_reason: 'IIT Madras. 15 years experience. AIR <100 students mentored.',
  },
  {
    id: '11',
    name: 'Meera Joshi',
    area: 'Kondapur',
    subjects: ['NEET Biology', 'CBSE Science'],
    distance_km: 3.0,
    rating: 4.3,
    rate: 750,
    photo_url: 'https://i.pravatar.cc/150?img=11',
    badges: ['Medical Pro'],
    ai_match_reason: 'Dentist by profession. Teaches NEET bio on weekends.',
  },
  {
    id: '12',
    name: 'Arjun Desai',
    area: 'Gachibowli',
    subjects: ['Coding', 'English'],
    distance_km: 2.1,
    rating: 4.7,
    rate: 650,
    photo_url: 'https://i.pravatar.cc/150?img=12',
    badges: ['Full Stack Dev'],
    ai_match_reason: 'MERN stack expert. Builds projects with students.',
  },
]